#! /bin/bash

show_question() {
  echo -e "\033[1;34m$@\033[0m"
}

show_dir() {
  echo -e "\033[1;32m$@\033[0m"
}

show_error() {
  echo -e "\033[1;31m$@\033[0m"
}

end() {
  echo -e "\nExiting...\n"
  exit 0
}

continue() {
  show_question "\nDo you want to continue? (y)es, (n)o : \n"
  read INPUT
  case $INPUT in
    [Yy]* ) ;;
    [Nn]* ) end;;
    * ) show_error "\nSorry, try again."; continue;;
  esac
}

replace() {
  show_question "\nFound an existing installation. Replace it? (y)es, (n)o :\n" 
  read INPUT
  case $INPUT in
    [Yy]* ) rm -rf $DEST_DIR/Stylish*;;
    [Nn]* ) ;;
    * ) show_error "\nSorry, try again."; replace $@;;
  esac
}

setup() {
  show_question "\nDo you want to set the theme now? (y)es, (n)o : \n"
  read INPUT
  case $INPUT in
    [Yy]* ) themes;;
    [Nn]* ) end;;
    * ) show_error "\nSorry, try again."; setup;;
  esac
}

themes() {
  show_question "\n+------------------------------------------------------------------+

      Select a number to set the theme you want:

              (a)  StylishDark
              (b)  StylishDark-Azul
              (c)  StylishDark-Jade
              (d)  StylishDark-Tang
              (e)  StylishDark-Laptop
              (f)  StylishDark-Laptop-Azul
              (g)  StylishDark-Laptop-Jade
              (h)  StylishDark-Laptop-Tang
              (i)  StylishLight
              (j)  StylishLight-Azul
              (k)  StylishLight-Jade
              (l)  StylishLight-Tang
              (m)  StylishLight-Laptop
              (n)  StylishLight-Laptop-Azul
              (o)  StylishLight-Laptop-Jade
              (p)  StylishLight-Laptop-Tang

+------------------------------------------------------------------+\n"
  read INPUT
  case $INPUT in
    [Aa]* )  StylishDark;;
    [Bb]* )  StylishDark-Azul;;
    [Cc]* )  StylishDark-Jade;;
    [Dd]* )  StylishDark-Tang;;
    [Ee]* )  StylishDark-Laptop;;
    [Ff]* )  StylishDark-Laptop-Azul;;
    [Gg]* )  StylishDark-Laptop-Jade;;
    [Hh]* )  StylishDark-Laptop-Tang;;
    [Ii]* )  StylishLight;;
    [Jj]* )  StylishLight-Azul;;
    [Kk]* )  StylishLight-Jade;;
    [Ll]* )  StylishLight-Tang;;
    [Mm]* )  StylishLight-Laptop;;
    [Nn]* )  StylishLight-Laptop-Azul;;
    [Oo]* )  StylishLight-Laptop-Jade;;
    [Pp]* )  StylishLight-Laptop-Tang;;
    * ) show_error "\nSorry, try again."; themes;;
  esac
}

StylishDark() {

# Set StylishDark Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme StylishDark
  gsettings set org.gnome.desktop.wm.preferences theme StylishDark
  echo "Done!"

}

StylishDark-Azul() {

# Set StylishDark-Azul Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme StylishDark-Azul
  gsettings set org.gnome.desktop.wm.preferences theme StylishDark-Azul
  echo "Done!"

}

StylishDark-Jade() {

# Set StylishDark-Jade Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme StylishDark-Jade
  gsettings set org.gnome.desktop.wm.preferences theme StylishDark-Jade
  echo "Done!"

}

StylishDark-Tang() {

# Set StylishDark-Tang Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme StylishDark-Tang
  gsettings set org.gnome.desktop.wm.preferences theme StylishDark-Tang
  echo "Done!"

}

StylishDark-Laptop() {

# Set StylishDark-Laptop Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme StylishDark-Laptop
  gsettings set org.gnome.desktop.wm.preferences theme StylishDark-Laptop
  echo "Done!"

}

StylishDark-Laptop-Azul() {

# Set StylishDark-Laptop-Azul Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme StylishDark-Laptop-Azul
  gsettings set org.gnome.desktop.wm.preferences theme StylishDark-Laptop-Azul
  echo "Done!"

}

StylishDark-Laptop-Jade() {

# Set StylishDark-Laptop-Jade Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme StylishDark-Laptop-Jade
  gsettings set org.gnome.desktop.wm.preferences theme StylishDark-Laptop-Jade
  echo "Done!"

}

StylishDark-Laptop-Tang() {

# Set StylishDark-Laptop-Tang Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme StylishDark-Laptop-Tang
  gsettings set org.gnome.desktop.wm.preferences theme StylishDark-Laptop-Tang
  echo "Done!"

}

StylishLight() {

# Set StylishLight Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme StylishLight
  gsettings set org.gnome.desktop.wm.preferences theme StylishLight
  echo "Done!"

}

StylishLight-Azul() {

# Set StylishLight-Azul Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme StylishLight-Azul
  gsettings set org.gnome.desktop.wm.preferences theme StylishLight-Azul
  echo "Done!"

}

StylishLight-Jade() {

# Set StylishLight-Jade Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme StylishLight-Jade
  gsettings set org.gnome.desktop.wm.preferences theme StylishLight-Jade
  echo "Done!"

}

StylishLight-Tang() {

# Set StylishLight-Tang Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme StylishLight-Tang
  gsettings set org.gnome.desktop.wm.preferences theme StylishLight-Tang
  echo "Done!"

}

StylishLight-Laptop() {

# Set StylishLight-Laptop Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme StylishLight-Laptop
  gsettings set org.gnome.desktop.wm.preferences theme StylishLight-Laptop
  echo "Done!"

}

StylishLight-Laptop-Azul() {

# Set StylishLight-Laptop-Azul Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme StylishLight-Laptop-Azul
  gsettings set org.gnome.desktop.wm.preferences theme StylishLight-Laptop-Azul
  echo "Done!"

}

StylishLight-Laptop-Jade() {

# Set StylishLight-Laptop-Jade Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme StylishLight-Laptop-Jade
  gsettings set org.gnome.desktop.wm.preferences theme StylishLight-Laptop-Jade
  echo "Done!"

}


StylishLight-Laptop-Tang() {

# Set StylishLight-Laptop-Tang Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme StylishLight-Laptop-Tang
  gsettings set org.gnome.desktop.wm.preferences theme StylishLight-Laptop-Tang
  echo "Done!"

}

install() {

  # PREVIEW

  # Show destination directory
  echo -e "\nStylish Gtk Theme will be installed in:\n"
  show_dir "\t$DEST_DIR"
  if [ "$UID" -eq "$ROOT_UID" ]; then
    echo -e "\nIt will be available to all users."
  else
    echo -e "\nIf you want to make them available to all users, run this script as root."
  fi

  continue

  # INSTALL

  # Check destination directory
  if [ ! -d $DEST_DIR ]; then
    mkdir -p $DEST_DIR
  elif [[ -d $DEST_DIR/StylishDark && -d $DEST_DIR/StylishDark-Azul && -d $DEST_DIR/StylishDark-Jade && -d $DEST_DIR/StylishDark-Tang && -d $DEST_DIR/StylishDark-Laptop && -d $DEST_DIR/StylishDark-Laptop-Azul && -d $DEST_DIR/StylishDark-Laptop-Jade && -d $DEST_DIR/StylishDark-Laptop-Tang && -d $DEST_DIR/StylishLight && -d $DEST_DIR/StylishLight-Azul && -d $DEST_DIR/StylishLight-Jade && -d $DEST_DIR/StylishLight-Tang && -d $DEST_DIR/StylishLight-Laptop && -d $DEST_DIR/StylishLight-Laptop-Azul && -d $DEST_DIR/StylishLight-Laptop-Jade && -d $DEST_DIR/StylishLight-Laptop-Tang ]]; then
    replace $DEST_DIR
  fi

  echo -e "\nInstalling Stylish..."
  
  # Copying files

  ./Install

  echo -e "\nInstallation complete!"

  setup

}

remove() {

  # PREVIEW

  # Show installation directory
  if [[ -d $DEST_DIR/StylishDark && -d $DEST_DIR/StylishDark-Azul && -d $DEST_DIR/StylishDark-Jade && -d $DEST_DIR/StylishDark-Tang && -d $DEST_DIR/StylishDark-Laptop && -d $DEST_DIR/StylishDark-Laptop-Azul && -d $DEST_DIR/StylishDark-Laptop-Jade && -d $DEST_DIR/StylishDark-Laptop-Tang && -d $DEST_DIR/StylishLight && -d $DEST_DIR/StylishLight-Azul && -d $DEST_DIR/StylishLight-Jade && -d $DEST_DIR/StylishLight-Tang && -d $DEST_DIR/StylishLight-Laptop && -d $DEST_DIR/StylishLight-Laptop-Azul && -d $DEST_DIR/StylishLight-Laptop-Jade && -d $DEST_DIR/StylishLight-Laptop-Tang ]]; then
    echo -e "\nStylish Gtk Themes installed in:\n"
    show_dir "\t$DEST_DIR"
    if [ "$UID" -eq "$ROOT_UID" ]; then
      echo -e "\nIt will remove for all users."
    else
      echo -e "\nIt will remove only for current user."
    fi

    continue
  
  else
    show_error "\nStylish Gtk Themes is not installed in:\n"
    show_dir "\t$DEST_DIR\n"
    end
  fi

  # REMOVE

  echo -e "\nRemoving Stylish ..."

  # Removing files

  rm -rf $DEST_DIR/Stylish*

  echo "Removing complete!"
  echo "I hope to see you soon."
}

main() {
  show_question "What you want to do: (i)nstall, (r)emove : \n"
  read INPUT
  case $INPUT in
    [Ii]* ) install;;
    [Rr]* ) remove;;
    * ) show_error "\nSorry, try again."; main;;
  esac
}

ROOT_UID=0
DEST_DIR=

# Destination directory
if [ "$UID" -eq "$ROOT_UID" ]; then
  DEST_DIR="/usr/share/themes"
else
  DEST_DIR="$HOME/.themes"
fi

echo -e "\e[1m\n+----------------------------------------------+"
echo -e "|      Stylish Gtk Theme Installer Script      |"
echo -e "+----------------------------------------------+\n\e[0m"

main
